package com.iqscaffold.pipelineservice.pipeline;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.List;
import java.util.Optional;

import com.iqscaffold.pipelineservice.shared.exception.BusinessException;
import com.iqscaffold.pipelineservice.shared.exception.ConflictException;
import com.iqscaffold.pipelineservice.shared.exception.ResourceNotFoundException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
@DisplayName("PipelineStageService Unit Tests")
class PipelineStageServiceImplTest {

  @Mock
  private PipelineStageRepository stageRepository;

  @Mock
  private PipelineItemRepository itemRepository;

  private PipelineStageServiceImpl service;

  private PipelineStage testStage;

  @BeforeEach
  void setUp() {
    service = new PipelineStageServiceImpl(stageRepository, itemRepository);

    testStage = new PipelineStage("New", 0);
    testStage.setId(1L);
    testStage.setIsActive(true);
    testStage.setIsFinalStage(false);
  }

  @Test
  @DisplayName("Should create stage with auto-generated display order")
  void shouldCreateStageWithAutoGeneratedOrder() {
    // Arrange
    PipelineStage newStage = new PipelineStage("Contacted", null);
    PipelineStage existingStage = new PipelineStage("New", 0);

    when(stageRepository.existsByName("Contacted")).thenReturn(false);
    when(stageRepository.findAllByOrderByDisplayOrderAsc()).thenReturn(List.of(existingStage));
    when(stageRepository.save(any(PipelineStage.class))).thenReturn(newStage);

    // Act
    PipelineStage result = service.createStage(newStage);

    // Assert
    assertThat(result).isNotNull();
    assertThat(newStage.getDisplayOrder()).isEqualTo(1);
    verify(stageRepository).save(newStage);
  }

  @Test
  @DisplayName("Should create stage with specified display order")
  void shouldCreateStageWithSpecifiedOrder() {
    // Arrange
    PipelineStage newStage = new PipelineStage("Contacted", 5);

    when(stageRepository.existsByName("Contacted")).thenReturn(false);
    when(stageRepository.save(any(PipelineStage.class))).thenReturn(newStage);

    // Act
    PipelineStage result = service.createStage(newStage);

    // Assert
    assertThat(result).isNotNull();
    assertThat(result.getDisplayOrder()).isEqualTo(5);
    verify(stageRepository).save(newStage);
  }

  @Test
  @DisplayName("Should throw exception when creating stage with duplicate name")
  void shouldThrowExceptionWhenCreatingDuplicateStage() {
    // Arrange
    when(stageRepository.existsByName("New")).thenReturn(true);

    // Act & Assert
    assertThatThrownBy(() -> service.createStage(testStage))
        .isInstanceOf(ConflictException.class);

    verify(stageRepository, never()).save(any());
  }

  @Test
  @DisplayName("Should get stage by ID")
  void shouldGetStageById() {
    // Arrange
    when(stageRepository.findById(1L)).thenReturn(Optional.of(testStage));

    // Act
    Optional<PipelineStage> result = service.getStageById(1L);

    // Assert
    assertThat(result).isPresent();
    assertThat(result.get().getId()).isEqualTo(1L);
  }

  @Test
  @DisplayName("Should get all stages ordered by display order")
  void shouldGetAllStages() {
    // Arrange
    PipelineStage stage1 = new PipelineStage("New", 0);
    PipelineStage stage2 = new PipelineStage("Contacted", 1);
    when(stageRepository.findAllByOrderByDisplayOrderAsc()).thenReturn(List.of(stage1, stage2));

    // Act
    List<PipelineStage> result = service.getAllStages();

    // Assert
    assertThat(result).hasSize(2);
    assertThat(result.get(0).getName()).isEqualTo("New");
    assertThat(result.get(1).getName()).isEqualTo("Contacted");
  }

  @Test
  @DisplayName("Should get only active stages")
  void shouldGetActiveStages() {
    // Arrange
    PipelineStage activeStage = new PipelineStage("New", 0);
    activeStage.setIsActive(true);
    when(stageRepository.findByIsActiveTrueOrderByDisplayOrderAsc()).thenReturn(List.of(activeStage));

    // Act
    List<PipelineStage> result = service.getActiveStages();

    // Assert
    assertThat(result).hasSize(1);
    assertThat(result.get(0).getIsActive()).isTrue();
  }

  @Test
  @DisplayName("Should update stage")
  void shouldUpdateStage() {
    // Arrange
    PipelineStage updates = new PipelineStage("Updated Name", 0);
    updates.setDescription("Updated description");
    updates.setIsActive(false);
    updates.setIsFinalStage(true);
    updates.setColorCode("#FF0000");
    updates.setUpdatedBy("user1");

    when(stageRepository.findById(1L)).thenReturn(Optional.of(testStage));
    when(stageRepository.existsByName("Updated Name")).thenReturn(false);
    when(stageRepository.save(any(PipelineStage.class))).thenReturn(testStage);

    // Act
    PipelineStage result = service.updateStage(1L, updates);

    // Assert
    assertThat(result).isNotNull();
    assertThat(testStage.getName()).isEqualTo("Updated Name");
    assertThat(testStage.getDescription()).isEqualTo("Updated description");
    verify(stageRepository).save(testStage);
  }

  @Test
  @DisplayName("Should throw exception when updating to duplicate name")
  void shouldThrowExceptionWhenUpdatingToDuplicateName() {
    // Arrange
    PipelineStage updates = new PipelineStage("Contacted", 0);

    when(stageRepository.findById(1L)).thenReturn(Optional.of(testStage));
    when(stageRepository.existsByName("Contacted")).thenReturn(true);

    // Act & Assert
    assertThatThrownBy(() -> service.updateStage(1L, updates))
        .isInstanceOf(ConflictException.class);
  }

  @Test
  @DisplayName("Should throw exception when updating non-existent stage")
  void shouldThrowExceptionWhenUpdatingNonExistentStage() {
    // Arrange
    when(stageRepository.findById(999L)).thenReturn(Optional.empty());

    // Act & Assert
    assertThatThrownBy(() -> service.updateStage(999L, testStage))
        .isInstanceOf(ResourceNotFoundException.class);
  }

  @Test
  @DisplayName("Should delete stage when no items in stage")
  void shouldDeleteStageWhenNoItems() {
    // Arrange
    when(stageRepository.findById(1L)).thenReturn(Optional.of(testStage));
    when(itemRepository.countByStageId(1L)).thenReturn(0L);

    // Act
    service.deleteStage(1L);

    // Assert
    verify(stageRepository).delete(testStage);
  }

  @Test
  @DisplayName("Should throw exception when deleting stage with items")
  void shouldThrowExceptionWhenDeletingStageWithItems() {
    // Arrange
    when(stageRepository.findById(1L)).thenReturn(Optional.of(testStage));
    when(itemRepository.countByStageId(1L)).thenReturn(5L);

    // Act & Assert
    assertThatThrownBy(() -> service.deleteStage(1L))
        .isInstanceOf(BusinessException.class)
        .hasMessageContaining("Cannot delete stage");

    verify(stageRepository, never()).delete(any());
  }

  @Test
  @DisplayName("Should throw exception when deleting non-existent stage")
  void shouldThrowExceptionWhenDeletingNonExistentStage() {
    // Arrange
    when(stageRepository.findById(999L)).thenReturn(Optional.empty());

    // Act & Assert
    assertThatThrownBy(() -> service.deleteStage(999L))
        .isInstanceOf(ResourceNotFoundException.class);
  }

  @Test
  @DisplayName("Should update stage order")
  void shouldUpdateStageOrder() {
    // Arrange
    PipelineStage stage1 = new PipelineStage("New", 0);
    stage1.setId(1L);
    PipelineStage stage2 = new PipelineStage("Contacted", 1);
    stage2.setId(2L);
    PipelineStage stage3 = new PipelineStage("Qualified", 2);
    stage3.setId(3L);

    when(stageRepository.findById(1L)).thenReturn(Optional.of(stage1));
    when(stageRepository.findAllByOrderByDisplayOrderAsc()).thenReturn(new java.util.ArrayList<>(List.of(stage1, stage2, stage3)));
    when(stageRepository.saveAll(any())).thenReturn(List.of(stage2, stage3, stage1));

    // Act - Move stage1 from position 0 to position 2
    PipelineStage result = service.updateStageOrder(1L, 2);

    // Assert
    assertThat(result).isNotNull();
    verify(stageRepository).saveAll(any());
  }

  @Test
  @DisplayName("Should not update order when new order equals old order")
  void shouldNotUpdateOrderWhenSameOrder() {
    // Arrange
    when(stageRepository.findById(1L)).thenReturn(Optional.of(testStage));

    // Act
    PipelineStage result = service.updateStageOrder(1L, 0);

    // Assert
    assertThat(result).isNotNull();
    verify(stageRepository, never()).saveAll(any());
  }

  @Test
  @DisplayName("Should throw exception when updating order of non-existent stage")
  void shouldThrowExceptionWhenUpdatingOrderOfNonExistentStage() {
    // Arrange
    when(stageRepository.findById(999L)).thenReturn(Optional.empty());

    // Act & Assert
    assertThatThrownBy(() -> service.updateStageOrder(999L, 1))
        .isInstanceOf(ResourceNotFoundException.class);
  }

  @Test
  @DisplayName("Should check if stage exists by name")
  void shouldCheckExistsByName() {
    // Arrange
    when(stageRepository.existsByName("New")).thenReturn(true);

    // Act
    boolean exists = service.existsByName("New");

    // Assert
    assertThat(exists).isTrue();
  }

  @Test
  @DisplayName("Should handle moving stage to end of list")
  void shouldHandleMovingStageToEnd() {
    // Arrange
    PipelineStage stage1 = new PipelineStage("New", 0);
    stage1.setId(1L);
    PipelineStage stage2 = new PipelineStage("Contacted", 1);
    stage2.setId(2L);

    when(stageRepository.findById(1L)).thenReturn(Optional.of(stage1));
    when(stageRepository.findAllByOrderByDisplayOrderAsc()).thenReturn(new java.util.ArrayList<>(List.of(stage1, stage2)));
    when(stageRepository.saveAll(any())).thenReturn(List.of(stage2, stage1));

    // Act - Move to position beyond list size
    service.updateStageOrder(1L, 10);

    // Assert
    verify(stageRepository).saveAll(any());
  }
}
